### PR TITLE
Make the LoxoneWebSocketIT more reliable

### LINKED ISSUE #83: Test "should retry on bad credentials" is flaky
```
cz.smarteon.loxone.LoxoneWebSocketIT > should retry on bad credentials STANDARD_ERROR
    [Test worker] TRACE cz.smarteon.loxone.LoxoneAuth - LoxoneAuth init start
    [Test worker] TRACE cz.smarteon.loxone.LoxoneAuth - Fetching ApiInfo start
    [Test worker] TRACE cz.smarteon.loxone.LoxoneAuth - Fetching ApiInfo finish
    [Test worker] TRACE cz.smarteon.loxone.LoxoneAuth - Fetching PublicKey start
    [Test worker] TRACE cz.smarteon.loxone.LoxoneAuth - Fetching PublicKey finish
    [Test worker] TRACE cz.smarteon.loxone.LoxoneCrypto - Created sharedKey: 75b6f3af25f823f4e68d252dabceec0e51b9157b22561b40b620c515765d36d8
    [Test worker] TRACE cz.smarteon.loxone.LoxoneCrypto - Created sharedKeyIv: 19f42359f5267ed712b30436f9f84136
    [Test worker] TRACE cz.smarteon.loxone.LoxoneAuth - LoxoneAuth init finish
    [Test worker] TRACE cz.smarteon.loxone.LoxoneWebSocket - (Re)opening websocket connection
    [WebSocketConnectReadThread-49] INFO cz.smarteon.loxone.LoxoneWebsocketClient - Opened
    [pool-4-thread-1] TRACE cz.smarteon.loxone.LoxoneCrypto - Created session key (in hex): 4513bd009cf6e2e84dd386c7931c3184e1fb58b230a330fd585599efd7250d4e7e74497bba060f06f11fb98a159a3ebfe0c6f84743e5b3ef6481e12110fa28cccc1ef000ef001a060761448474759e474f9dbdb9a81e567f014695989ec07f8817e1763a21db548c3db604f28ffc2a18ee4e015fff457ba4f9729af1f5a27a16
    [pool-4-thread-1] DEBUG cz.smarteon.loxone.LoxoneWebSocket - Sending websocket message: jdev/sys/keyexchange/RRO9AJz24uhN04bHkxwxhOH7WLIwozD9WFWZ79clDU5+dEl7ugYPBvEfuYoVmj6/4Mb4R0Pls+9kgeEhEPoozMwe8ADvABoGB2FEhHR1nkdPnb25qB5WfwFGlZiewH+IF+F2OiHbVIw9tgTyj/wqGO5OAV//RXuk+XKa8fWiehY=
    [WebSocketConnectReadThread-49] TRACE cz.smarteon.loxone.LoxoneWebsocketClient - Incoming message {"LL":{"control":"dev/sys/keyexchange/RRO9AJz24uhN04bHkxwxhOH7WLIwozD9WFWZ79clDU5+dEl7ugYPBvEfuYoVmj6/4Mb4R0Pls+9kgeEhEPoozMwe8ADvABoGB2FEhHR1nkdPnb25qB5WfwFGlZiewH+IF+F2OiHbVIw9tgTyj/wqGO5OAV//RXuk+XKa8fWiehY=","code":200,"value":null}}
    [WebSocketConnectReadThread-49] ERROR cz.smarteon.loxone.LoxoneWebSocket - No command expected!
    java.util.NoSuchElementException
    	at java.base/java.util.AbstractQueue.remove(AbstractQueue.java:117)
    	at cz.smarteon.loxone.LoxoneWebSocket.processMessage(LoxoneWebSocket.java:319)
    	at cz.smarteon.loxone.LoxoneWebsocketClient.onMessage(LoxoneWebsocketClient.java:88)
    	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:500)
    	at org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:858)
    	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:792)
    	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:381)
    	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:218)
    	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:425)
    	at java.base/java.lang.Thread.run(Thread.java:834)
    [pool-4-thread-1] DEBUG cz.smarteon.loxone.LoxoneWebSocket - Sending websocket message: jdev/sys/getkey2/mocker
    [WebSocketConnectReadThread-49] TRACE cz.smarteon.loxone.LoxoneWebsocketClient - Incoming message {"LL":{"control":"jdev/sys/getkey2/mocker","code":200,"value":{"key":"41434633443134324337383441373035453333424344364133373431333430413642333442334244","salt":"31306137336533622D303163352D313732662D66666666616362383139643462636139","hashAlg":"SHA1"}}}
    [WebSocketConnectReadThread-49] INFO cz.smarteon.loxone.LoxoneWebsocketClient - Closed by local end because of 1000: 
    [Test worker] INFO cz.smarteon.loxone.LoxoneWebSocket - Connection or authentication failed, retrying...
    [Test worker] TRACE cz.smarteon.loxone.LoxoneWebSocket - (Re)opening websocket connection
    [WebSocketConnectReadThread-53] INFO cz.smarteon.loxone.LoxoneWebsocketClient - Opened
    [pool-4-thread-1] TRACE cz.smarteon.loxone.LoxoneCrypto - Created session key (in hex): 03407c5ab63f7de15f2230ed44e712548dfd46b9f6b444141e8c522f6366990b338c664851d9e4e02f6c146758a29661c388de16a951c35c8f28904858bb80fce7b10d1d8deb2883e72ec42e2d0a11defe0d84eb36429608d758b080b3737a590e9710851c806c78d52b9a92e85cb0ec6fe7741a0c7be9eccca23558cfdb2d37
    [pool-4-thread-1] DEBUG cz.smarteon.loxone.LoxoneWebSocket - Sending websocket message: jdev/sys/keyexchange/A0B8WrY/feFfIjDtROcSVI39Rrn2tEQUHoxSL2NmmQszjGZIUdnk4C9sFGdYopZhw4jeFqlRw1yPKJBIWLuA/OexDR2N6yiD5y7ELi0KEd7+DYTrNkKWCNdYsICzc3pZDpcQhRyAbHjVK5qS6Fyw7G/ndBoMe+nszKI1WM/bLTc=
    [pool-4-thread-1] DEBUG cz.smarteon.loxone.LoxoneWebSocket - Sending websocket message: jdev/sys/getkey2/mocker
    [WebSocketConnectReadThread-53] TRACE cz.smarteon.loxone.LoxoneWebsocketClient - Incoming message {"LL":{"control":"dev/sys/keyexchange/A0B8WrY/feFfIjDtROcSVI39Rrn2tEQUHoxSL2NmmQszjGZIUdnk4C9sFGdYopZhw4jeFqlRw1yPKJBIWLuA/OexDR2N6yiD5y7ELi0KEd7+DYTrNkKWCNdYsICzc3pZDpcQhRyAbHjVK5qS6Fyw7G/ndBoMe+nszKI1WM/bLTc=","code":200,"value":null}}
    [WebSocketConnectReadThread-53] ERROR cz.smarteon.loxone.LoxoneWebSocket - Can't parse response: Cannot construct instance of `cz.smarteon.loxone.message.LoxoneMessage`, problem: value can't be null
     at [Source: (String)"{"LL":{"control":"dev/sys/keyexchange/A0B8WrY/feFfIjDtROcSVI39Rrn2tEQUHoxSL2NmmQszjGZIUdnk4C9sFGdYopZhw4jeFqlRw1yPKJBIWLuA/OexDR2N6yiD5y7ELi0KEd7+DYTrNkKWCNdYsICzc3pZDpcQhRyAbHjVK5qS6Fyw7G/ndBoMe+nszKI1WM/bLTc=","code":200,"value":null}}"; line: 1, column: 236]
    [WebSocketConnectReadThread-53] TRACE cz.smarteon.loxone.LoxoneWebsocketClient - Incoming message {"LL":{"control":"jdev/sys/getkey2/mocker","code":200,"value":{"key":"41434633443134324337383441373035453333424344364133373431333430413642333442334244","salt":"31306137336533622D303163352D313732662D66666666616362383139643462636139","hashAlg":"SHA1"}}}
    [WebSocketConnectReadThread-53] INFO cz.smarteon.loxone.LoxoneWebsocketClient - Closed by local end because of 1000: 
    [Test worker] INFO cz.smarteon.loxone.LoxoneWebSocket - Connection or authentication failed, retrying...
    [Test worker] TRACE cz.smarteon.loxone.LoxoneWebSocket - (Re)opening websocket connection
    [WebSocketConnectReadThread-56] INFO cz.smarteon.loxone.LoxoneWebsocketClient - Opened
    [pool-4-thread-1] TRACE cz.smarteon.loxone.LoxoneCrypto - Created session key (in hex): 205648f34d55a1bac267103bd9b1cde833eed2853d654f4cf7c7c550fe0d218508ed2f5cea85420ca8a3191b183bfbbf7bdd56e3cd13c990c9b01d47081b1d42a4c4c5a9371b6583989917ed3819ac0745c75cc0a8ea075d31a597e11568c1309ce3e0e3033dc1d11a64b9b29c8c329dd09d7e24e97011b01c0b4486776b5130
    [pool-4-thread-1] DEBUG cz.smarteon.loxone.LoxoneWebSocket - Sending websocket message: jdev/sys/keyexchange/IFZI801VobrCZxA72bHN6DPu0oU9ZU9M98fFUP4NIYUI7S9c6oVCDKijGRsYO/u/e91W480TyZDJsB1HCBsdQqTExak3G2WDmJkX7TgZrAdFx1zAqOoHXTGll+EVaMEwnOPg4wM9wdEaZLmynIwyndCdfiTpcBGwHAtEhndrUTA=
    [pool-4-thread-1] DEBUG cz.smarteon.loxone.LoxoneWebSocket - Sending websocket message: jdev/sys/getkey2/mocker
    [WebSocketConnectReadThread-56] TRACE cz.smarteon.loxone.LoxoneWebsocketClient - Incoming message {"LL":{"control":"dev/sys/keyexchange/IFZI801VobrCZxA72bHN6DPu0oU9ZU9M98fFUP4NIYUI7S9c6oVCDKijGRsYO/u/e91W480TyZDJsB1HCBsdQqTExak3G2WDmJkX7TgZrAdFx1zAqOoHXTGll+EVaMEwnOPg4wM9wdEaZLmynIwyndCdfiTpcBGwHAtEhndrUTA=","code":200,"value":null}}
    [WebSocketConnectReadThread-56] ERROR cz.smarteon.loxone.LoxoneWebSocket - Can't parse response: Cannot construct instance of `cz.smarteon.loxone.message.LoxoneMessage`, problem: value can't be null
     at [Source: (String)"{"LL":{"control":"dev/sys/keyexchange/IFZI801VobrCZxA72bHN6DPu0oU9ZU9M98fFUP4NIYUI7S9c6oVCDKijGRsYO/u/e91W480TyZDJsB1HCBsdQqTExak3G2WDmJkX7TgZrAdFx1zAqOoHXTGll+EVaMEwnOPg4wM9wdEaZLmynIwyndCdfiTpcBGwHAtEhndrUTA=","code":200,"value":null}}"; line: 1, column: 236]
    [WebSocketConnectReadThread-56] TRACE cz.smarteon.loxone.LoxoneWebsocketClient - Incoming message {"LL":{"control":"jdev/sys/getkey2/mocker","code":200,"value":{"key":"41434633443134324337383441373035453333424344364133373431333430413642333442334244","salt":"31306137336533622D303163352D313732662D66666666616362383139643462636139","hashAlg":"SHA1"}}}
    [WebSocketConnectReadThread-56] INFO cz.smarteon.loxone.LoxoneWebsocketClient - Closed by local end because of 1000: 
    [Test worker] INFO cz.smarteon.loxone.LoxoneWebSocket - Connection or authentication failed, retrying...
    [Test worker] TRACE cz.smarteon.loxone.LoxoneWebSocket - (Re)opening websocket connection
    [WebSocketConnectReadThread-59] INFO cz.smarteon.loxone.LoxoneWebsocketClient - Opened
    [pool-4-thread-1] TRACE cz.smarteon.loxone.LoxoneCrypto - Created session key (in hex): 3ec89932c02905c3584f38fa61d56255da09a8882ab03926e511def592d6dbd2730e54908f5a4d3fa66f0063bd546acc7f820ae8cad7d1901b7ad4f1103a392ea4981760fe73061ee740b688781ab0ec52544b49bc473f3c74d36e34a7fd0a39338c5e9ba211fa1862c4ea97b7907d6fb10dbf2605817f5b758ce53e98505d7c
    [pool-4-thread-1] DEBUG cz.smarteon.loxone.LoxoneWebSocket - Sending websocket message: jdev/sys/keyexchange/PsiZMsApBcNYTzj6YdViVdoJqIgqsDkm5RHe9ZLW29JzDlSQj1pNP6ZvAGO9VGrMf4IK6MrX0ZAbetTxEDo5LqSYF2D+cwYe50C2iHgasOxSVEtJvEc/PHTTbjSn/Qo5M4xem6IR+hhixOqXt5B9b7ENvyYFgX9bdYzlPphQXXw=
    [pool-4-thread-1] DEBUG cz.smarteon.loxone.LoxoneWebSocket - Sending websocket message: jdev/sys/getkey2/mocker
    [WebSocketConnectReadThread-59] TRACE cz.smarteon.loxone.LoxoneWebsocketClient - Incoming message {"LL":{"control":"dev/sys/keyexchange/PsiZMsApBcNYTzj6YdViVdoJqIgqsDkm5RHe9ZLW29JzDlSQj1pNP6ZvAGO9VGrMf4IK6MrX0ZAbetTxEDo5LqSYF2D+cwYe50C2iHgasOxSVEtJvEc/PHTTbjSn/Qo5M4xem6IR+hhixOqXt5B9b7ENvyYFgX9bdYzlPphQXXw=","code":200,"value":null}}
    [WebSocketConnectReadThread-59] ERROR cz.smarteon.loxone.LoxoneWebSocket - Can't parse response: Cannot construct instance of `cz.smarteon.loxone.message.LoxoneMessage`, problem: value can't be null
     at [Source: (String)"{"LL":{"control":"dev/sys/keyexchange/PsiZMsApBcNYTzj6YdViVdoJqIgqsDkm5RHe9ZLW29JzDlSQj1pNP6ZvAGO9VGrMf4IK6MrX0ZAbetTxEDo5LqSYF2D+cwYe50C2iHgasOxSVEtJvEc/PHTTbjSn/Qo5M4xem6IR+hhixOqXt5B9b7ENvyYFgX9bdYzlPphQXXw=","code":200,"value":null}}"; line: 1, column: 236]
    [WebSocketConnectReadThread-59] TRACE cz.smarteon.loxone.LoxoneWebsocketClient - Incoming message {"LL":{"control":"jdev/sys/getkey2/mocker","code":200,"value":{"key":"41434633443134324337383441373035453333424344364133373431333430413642333442334244","salt":"31306137336533622D303163352D313732662D66666666616362383139643462636139","hashAlg":"SHA1"}}}
    [WebSocketConnectReadThread-59] INFO cz.smarteon.loxone.LoxoneWebsocketClient - Closed by local end because of 1000: 
    [Test worker] INFO cz.smarteon.loxone.LoxoneWebSocket - Connection or authentication failed, retrying...
    [Test worker] TRACE cz.smarteon.loxone.LoxoneWebSocket - (Re)opening websocket connection
    [WebSocketConnectReadThread-62] INFO cz.smarteon.loxone.LoxoneWebsocketClient - Opened
    [pool-4-thread-1] TRACE cz.smarteon.loxone.LoxoneCrypto - Created session key (in hex): 4b078c0cbb7c4ed0400f0586876bcf3f58bac52bdaa02195a014fef9eadbfee8132d33685c5bde40a3ff18ebcd0f4fdec59db4e59a0f645f41ae8cd2cea76903a12803e00a4f2c2b39d0da35c1829619aa8de97a693e743c8e22059761e611c8f8bd2070275249afe4efc13f8dbca0e180e585cffa078025760462c51193c481
    [pool-4-thread-1] DEBUG cz.smarteon.loxone.LoxoneWebSocket - Sending websocket message: jdev/sys/keyexchange/SweMDLt8TtBADwWGh2vPP1i6xSvaoCGVoBT++erb/ugTLTNoXFveQKP/GOvND0/exZ205ZoPZF9BrozSzqdpA6EoA+AKTywrOdDaNcGClhmqjel6aT50PI4iBZdh5hHI+L0gcCdSSa/k78E/jbyg4YDlhc/6B4AldgRixRGTxIE=
    [pool-4-thread-1] DEBUG cz.smarteon.loxone.LoxoneWebSocket - Sending websocket message: jdev/sys/getkey2/mocker
    [WebSocketConnectReadThread-62] TRACE cz.smarteon.loxone.LoxoneWebsocketClient - Incoming message {"LL":{"control":"dev/sys/keyexchange/SweMDLt8TtBADwWGh2vPP1i6xSvaoCGVoBT++erb/ugTLTNoXFveQKP/GOvND0/exZ205ZoPZF9BrozSzqdpA6EoA+AKTywrOdDaNcGClhmqjel6aT50PI4iBZdh5hHI+L0gcCdSSa/k78E/jbyg4YDlhc/6B4AldgRixRGTxIE=","code":200,"value":null}}
    [WebSocketConnectReadThread-62] ERROR cz.smarteon.loxone.LoxoneWebSocket - Can't parse response: Cannot construct instance of `cz.smarteon.loxone.message.LoxoneMessage`, problem: value can't be null
     at [Source: (String)"{"LL":{"control":"dev/sys/keyexchange/SweMDLt8TtBADwWGh2vPP1i6xSvaoCGVoBT++erb/ugTLTNoXFveQKP/GOvND0/exZ205ZoPZF9BrozSzqdpA6EoA+AKTywrOdDaNcGClhmqjel6aT50PI4iBZdh5hHI+L0gcCdSSa/k78E/jbyg4YDlhc/6B4AldgRixRGTxIE=","code":200,"value":null}}"; line: 1, column: 236]
    [WebSocketConnectReadThread-62] TRACE cz.smarteon.loxone.LoxoneWebsocketClient - Incoming message {"LL":{"control":"jdev/sys/getkey2/mocker","code":200,"value":{"key":"41434633443134324337383441373035453333424344364133373431333430413642333442334244","salt":"31306137336533622D303163352D313732662D66666666616362383139643462636139","hashAlg":"SHA1"}}}
    [WebSocketConnectReadThread-62] INFO cz.smarteon.loxone.LoxoneWebsocketClient - Closed by local end because of 1000: 
    [Test worker] INFO cz.smarteon.loxone.LoxoneWebSocket - Connection or authentication failed, retrying...
    [Test worker] TRACE cz.smarteon.loxone.LoxoneWebSocket - (Re)opening websocket connection
    [WebSocketConnectReadThread-65] INFO cz.smarteon.loxone.LoxoneWebsocketClient - Opened
    [pool-4-thread-1] TRACE cz.smarteon.loxone.LoxoneCrypto - Created session key (in hex): 50ded0cfda6c151f5e130f56d4b2b772e300bed3be30cb98d9be711d978a2e575785a0279cbffc6476ad9876af88133ba865a8d6e7b0f055a1f2f85ef0fb0e2047d0241983757c433b29533f2b592675525d86c46d1768e857b43f4f988ba710a30a319c97d56381681286f216d09dfa75293477d1d6b0fc7da05eb6894d2757
    [pool-4-thread-1] DEBUG cz.smarteon.loxone.LoxoneWebSocket - Sending websocket message: jdev/sys/keyexchange/UN7Qz9psFR9eEw9W1LK3cuMAvtO+MMuY2b5xHZeKLldXhaAnnL/8ZHatmHaviBM7qGWo1uew8FWh8vhe8PsOIEfQJBmDdXxDOylTPytZJnVSXYbEbRdo6Fe0P0+Yi6cQowoxnJfVY4FoEobyFtCd+nUpNHfR1rD8faBetolNJ1c=
    [pool-4-thread-1] DEBUG cz.smarteon.loxone.LoxoneWebSocket - Sending websocket message: jdev/sys/getkey2/mocker
    [WebSocketConnectReadThread-65] TRACE cz.smarteon.loxone.LoxoneWebsocketClient - Incoming message {"LL":{"control":"dev/sys/keyexchange/UN7Qz9psFR9eEw9W1LK3cuMAvtO+MMuY2b5xHZeKLldXhaAnnL/8ZHatmHaviBM7qGWo1uew8FWh8vhe8PsOIEfQJBmDdXxDOylTPytZJnVSXYbEbRdo6Fe0P0+Yi6cQowoxnJfVY4FoEobyFtCd+nUpNHfR1rD8faBetolNJ1c=","code":200,"value":null}}
    [WebSocketConnectReadThread-65] ERROR cz.smarteon.loxone.LoxoneWebSocket - Can't parse response: Cannot construct instance of `cz.smarteon.loxone.message.LoxoneMessage`, problem: value can't be null
     at [Source: (String)"{"LL":{"control":"dev/sys/keyexchange/UN7Qz9psFR9eEw9W1LK3cuMAvtO+MMuY2b5xHZeKLldXhaAnnL/8ZHatmHaviBM7qGWo1uew8FWh8vhe8PsOIEfQJBmDdXxDOylTPytZJnVSXYbEbRdo6Fe0P0+Yi6cQowoxnJfVY4FoEobyFtCd+nUpNHfR1rD8faBetolNJ1c=","code":200,"value":null}}"; line: 1, column: 236]
    [WebSocketConnectReadThread-65] TRACE cz.smarteon.loxone.LoxoneWebsocketClient - Incoming message {"LL":{"control":"jdev/sys/getkey2/mocker","code":200,"value":{"key":"41434633443134324337383441373035453333424344364133373431333430413642333442334244","salt":"31306137336533622D303163352D313732662D66666666616362383139643462636139","hashAlg":"SHA1"}}}
    [WebSocketConnectReadThread-65] INFO cz.smarteon.loxone.LoxoneWebsocketClient - Closed by local end because of 1000: 
    [Test worker] INFO cz.smarteon.loxone.LoxoneWebSocket - Connection or authentication failed too many times, give up
```

Could be related to #81

### PR DESCRIPTION
**Pull request by jimirocks**
by adding processing delay to MockWebSocketServer the test is closer to real miniserver behaviour. However the race condition is still there.

Resolves #83

### CODE REVIEW

File: src/main/java/cz/smarteon/loxone/LoxoneWebSocket.java [hunk 1]
```diff
@@ -305,6 +305,8 @@ private void waitForRetry() {
     }
 
 
+    // TODO Contains potential race condition when response to the sent command is received faster than command is added to queue
+    // however, the probability it happens with real miniserver is very low
```
Comment (PetrZufan) [inline src/main/java/cz/smarteon/loxone/LoxoneWebSocket.java]: Couldn`t be easily solved by switching the order of commands?
```
if (! KEEP_ALIVE.getCommand().equals(command.getCommand())) {
    commands.add(command);
}
webSocketClient.send(command.getCommand());
```

Comment (xzavrel) [reply src/main/java/cz/smarteon/loxone/LoxoneWebSocket.java]: It couldn't be solved easily. If you switch order of statements and `websocket.send()` won't process correctly the commands list have inconsistent state. The proper solution is to make the section critical.

Comment (jimirocks) [reply src/main/java/cz/smarteon/loxone/LoxoneWebSocket.java]: Adding another `ReadWriteLock` and guarding all the access to the commands is most correct and relatively easy to implement. The down side is the code readability and slight perf decrease. Considering in reality this race condition could in fact happen only in case the network round trip and miniserver processing will happen in less than few dozens of milliseconds it's probably not worth to add critical section handling here.

Comment (PetrZufan) [reply src/main/java/cz/smarteon/loxone/LoxoneWebSocket.java]: ok, now I see it, thx for explanation.
